### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by ThangBK2009** [nv95/OpenManga#15]
+ Please add Tab: Downloaded and Download queue to menu
+ In Reading screen: touch screen to show option menu (dont need tap to right corner button); 
improve smooth when next page.
+ Auto download new chapter of Manga in favorite

Thanks.

**Comment by Koitharu** [comment]
> Downloaded and Download queue to menu

Local storage (first item) = Downloaded

Download queue is available only if active downloads are exist and available from notification

**Comment by ThangBK2009** [comment]
please add Tab: "Latest update" to follow manga more easily

**Comment by ThangBK2009** [comment]
The float button hide when scroll up,flease fix Float button show when scroll down

**Comment by Koitharu** [comment]
> fix Float button show when scroll down
Fixed in d56b79551a31cef879e750b40cb5b569062b51f1
