### ISSUE TITLE
Stopped working after 3.1 update

### ISSUE THREAD

**Issue by swamp-fish** [nv95/OpenManga#18]
Android 6, Samsung J7. After i updated to 3.1 it stopped working and i can't revert back to old version by using f-droid.

**Comment by Koitharu** [comment]
What you mean under "stopped working"?
Please, provide more details (log, etc.)

**Comment by swamp-fish** [comment]
When i tap to open it, it says "Unforunately, OpenManga has stopped" and shuts down.
Where can i find a log?

**Comment by Koitharu** [comment]
Log file is 
~/Android/data/org.nv95.openmanga/files/debug/log.txt

**Comment by swamp-fish** [comment]
Hi, i've tried the new version, it works again.
