### ISSUE TITLE
Some issue and ideas

### ISSUE THREAD

**Issue by NovaPlay7** [nv95/OpenManga#25]
_ ImageLoader can't download https images urls but Picasso can if you can switch to picasso.

_ it will be better if you save MangaInfo as bundle in manga file so that when you open local storage app open that MangaInfo and add it to list with all the references to chapters in file
that way we can move manga , export ,and import without problem

_ add ability to select multiple genres for specific providers

_ if you can make download the new app version in 2 case 
1-obligate : so you have to install it to run the app
2-optional : as it is now

_ add related button in PreviewActivity to search for manga name in other sources (that way you can find which one have new chapters)

_ is there any way to add comment section on manga PreviewActivity saved on server database along with sync accounts?

and finally i wanna thank you for this great open source it absolutely the best.

**Comment by Koitharu** [comment]
> comment section

Good idea. Maybe later, so now sync server is unstable

> download https images

What reasons to use https for images? I think it is not important

**Comment by NovaPlay7** [comment]
There is some sites using https urls for images in that case i used picasso to download them 
If no one else have this problem there is no need to change it.
