### ISSUE TITLE
can not Register new account to synchronize history and favorites

### ISSUE THREAD

**Issue by vandong123** [nv95/OpenManga#28]
Please fix the error please. I can not register new account. It keep loading overtime.  And it shows up a small window "Authorization failed, failed to connect to /46.36.36.38 port 5000 after 15000ms".
I want to synchronize to move history and favorite to new device

**Comment by vandong123** [comment]
And one more issue, when i use webtoon mode, the images are overlap eachother

**Comment by hburaktasyurek** [comment]
That's because server is down. You can use your own server by using [OpenManga-sync](https://github.com/nv95/OpenManga-sync)

**Comment by vandong123** [comment]
i try to set up own server. but i got error 404. can i contact you for more details.

**Comment by hburaktasyurek** [comment]
Can you write your server details? Write here so others can use later.

**Comment by vandong123** [comment]
Thank u, I send you my log
```
root@myubuntu16:~/OpenManga-sync# export FLASK_APP=/root/OpenManga-sync/api/app.py
root@myubuntu16:~/OpenManga-sync# flask run --host=0.0.0.0
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
 * Serving Flask app "api.app"
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[IP of my phone running app] - - [03/Sep/2017 17:28:50] "PUT /api/v1/user HTTP/1.1" 404 -
```

**Comment by vandong123** [comment]
On manga App, it shows a window when i register account. "Authorization failed. Value <!DOCTYPE of type java.lang.String can not be converted to JSONObject"

**Comment by hburaktasyurek** [comment]
Did you quit before check with your phone? And are you working locally?

**Comment by vandong123** [comment]
You mean "Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)"
No, I keep flark running while i check with my phone. And i run it on a vps server, not local

**Comment by vandong123** [comment]
does your server run well? can you show me step by step to set up it right

**Comment by vandong123** [comment]
here is my config.py
`
class Config(object):
        DEBUG = True
        HOST_IP = '127.0.0.1'
        SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:123456@127.0.0.1/openmanga'
        SQLALCHEMY_NATIVE_UNICODE = True
        SQLALCHEMY_ECHO = True
`

**Comment by hburaktasyurek** [comment]
1. I downloaded Open Manga SYNC
2. Created a databese and upload sql file.
3. Edited config.py according to my database
4. I install python 3.6 to my server(centos)
5. İnstall requipments.
7. Send SYNC files to a directory on server
8. Go to api directory
9. Run python app.py

**Comment by vandong123** [comment]
Yes I understand now. thank u. let me take a try

**Comment by hburaktasyurek** [comment]
You should have a database server like MySQL. An you should upload db.sql file to database that you are create.

**Comment by vandong123** [comment]
Yes I did step 2.

**Comment by hburaktasyurek** [comment]
And dont use 127.0.0.1 for host ip. Use your server ip

**Comment by vandong123** [comment]
i am removing python2.7 and python3.5. Then i install python3.6

**Comment by vandong123** [comment]
Step5: İnstall requipments.
I type command: "pip install -r requirement.txt"
Is that enough? or i have to run "python setup.py install"

**Comment by vandong123** [comment]
this is log when i run python app.py

`root@myubuntu16:~/OpenManga-sync/api# python app.py

/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "app.py", line 38, in <module>
    app.run(host=app.config['HOST_IP'])
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

root@myubuntu16:~/OpenManga-sync/api# 
`

**Comment by hburaktasyurek** [comment]
No, You shoud type like "pip install flask"

**Comment by vandong123** [comment]
this is log when i run "python app.py"

`root@myubuntu16:~/OpenManga-sync/api# python app.py

/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:839: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "app.py", line 38, in <module>
    app.run(host=app.config['HOST_IP'])
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 841, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 720, in run_simple
    s.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address
`

**Comment by vandong123** [comment]
this is config.py

`class Config(object):
        DEBUG = True
        HOST_IP = '<myserver_publishIP>'
        SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:<mysql_passwd>@<myserver_publishIP>/openmanga'
        SQLALCHEMY_NATIVE_UNICODE = True
        SQLALCHEMY_ECHO = True
`

**Comment by vandong123** [comment]
the problem may be come from python2.7. it is not totally remove after i run apt-get remove --purge python2.7

**Comment by vandong123** [comment]
Thank you so much
