### ISSUE TITLE
Broken ratings in some sources

### ISSUE THREAD

**Issue by substanceof** [nv95/OpenManga#39]
Mangachan/hentai-chan and MangaReader sources both shows zero ratings for all items

![](https://i.imgur.com/nE0VzWq.jpg)
![](https://i.imgur.com/Rm2cOdp.jpg)

**Comment by Koitharu** [comment]
Rating is not supported by some sources

**Comment by substanceof** [comment]
Maybe then just hide rating when  it's equals zero?

**Comment by Koitharu** [comment]
Maybe)
