### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by ghost** [nv95/OpenManga#43]
I'm on V4.2 from F-Droid and i can't update to V4.4.1 from your app

**Comment by mangaMag** [comment]
Why don't you try to Remove the app and install it again

**Comment by ghost** [comment]
Ok but issue remains unfixed

**Comment by Koitharu** [comment]
Apks from f-droid have another signature, so, you cannot install apk, built by myself, above app, installed from f-droid. This is not an issue

**Comment by ghost** [comment]
Ok, IMHO you should disabled this feature for people who update your app via F-droid, it would make more sense

**Comment by Koitharu** [comment]
Yes, but sometimes I forgot this)
