### ISSUE TITLE
A little issue when Opening the source code

### ISSUE THREAD

**Issue by mangaMag** [nv95/OpenManga#52]
I have this issue when i downloaded the source code and compile it my self and i got this issue

```
For input string: ""
Open File
```

So i did open the file and it take me to the `build.grable` of the app and every thing seems good

Here is a screenshot : http://prntscr.com/ljykma

**Comment by mar4elkin** [comment]
I have same problem

**Comment by mar4elkin** [comment]
try to use stable version

**Comment by mar4elkin** [comment]
![image](https://user-images.githubusercontent.com/26876842/55591123-6758b880-573d-11e9-885d-538b1236e3cd.png)
