### ISSUE TITLE
Help in adding a new server

### ISSUE THREAD

**Issue by midou221** [nv95/OpenManga#70]
i tried to add a new server
But it doesn't work

i dont know if typed the right way
Are there any code ?
(sorry I recently started learning Java & jsoup)

`package org.nv95.openmanga.providers;

import android.content.Context;
import androidx.annotation.Nullable;
import android.text.Html;

import org.json.JSONArray;
import org.json.JSONObject;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.nv95.openmanga.R;
import org.nv95.openmanga.items.MangaChapter;
import org.nv95.openmanga.feature.manga.domain.MangaInfo;
import org.nv95.openmanga.items.MangaPage;
import org.nv95.openmanga.items.MangaSummary;
import org.nv95.openmanga.lists.MangaList;
import org.nv95.openmanga.utils.AppHelper;

import java.net.URLEncoder;
import java.util.ArrayList;

/**
 * Created by admin on 19.07.17.
 */

public class OnManga extends MangaProvider {

    private static final int sorts[] = {R.string.sort_alphabetical, R.string.sort_popular};
    private static final String sortUrls[] = {"name&asc=true", "views&asc=false"};

    private static final int genres[] = {
            R.string.genre_all, R.string.genre_adventure,R.string.action_genre,R.string.demons_genre,
            R.string.genre_comedy, R.string.genre_ecchi,R.string.genre_drama, R.string.genre_hentai, R.string.genre_sfiction,
            R.string.genre_historical, R.string.genre_harem, R.string.genre_josei, R.string.genre_horror, R.string.genre_mature,
            R.string.genre_art, R.string.genre_mystery, R.string.genre_mecha, R.string.genre_psychological, R.string.genre_oneshot,
            R.string.genre_school, R.string.genre_romance, R.string.genre_seinen, R.string.genre_fantasy,
            R.string.genre_shoujo_ai, R.string.genre_shoujo, R.string.genre_shounen_ai, R.string.genre_shounen, R.string.genre_sports,
            R.string.genre_slice_of_life, R.string.genre_supernatural, R.string.genre_natural, R.string.genre_vampires,
            R.string.genre_tragedy, R.string.genre_webtoon, R.string.genre_magic, R.string.genre_doujinshi
    };

    private static final int genreUrls[] = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36};

    public OnManga (Context context) {
        super(context);
    }

    @Override
    public MangaList getList(int page, int sort, int genre) throws Exception {
        MangaList list = new MangaList();
        Document document = getPage("https://www.on-manga.me/manga-list?page=" + (page + 1)
                + "&cat=" + (genre == 0 ? "" : genreUrls[genre - 1]) + "&alpha=&sortBy="
                + sortUrls[sort] + "&author=&tag=");
        MangaInfo manga;
        for (Element o : document.select("stylesheet")) {
            manga = new MangaInfo();
            manga.name = o.select("a.chart-title").first().text();
            manga.subtitle = null;
            try {
                manga.genres = o.select("div").last().previousElementSibling().text();
            } catch (Exception e) {
                manga.genres = "";
            }
            manga.path = o.select("a").first().attr("href");
            try {
                manga.preview = o.select("img").first().attr("src");
            } catch (Exception e) {
                manga.preview = "";
            }
            try {
                String scr = o.select("script").first().html();
                int p1 = scr.lastIndexOf('"');
                int p0 = scr.lastIndexOf('"', p1 - 1);
                manga.rating = (byte) (Float.parseFloat(scr.substring(p0 + 1, p1)) * 20);
            } catch (Exception ignored) {
            }
            //manga.rating = (byte) (Byte.parseByte(o.select("span.rate").first().text().substring(0,3).replace(".","")) * 2);
            manga.provider = OnManga.class;
            manga.id = manga.path.hashCode();
            list.add(manga);
        }
        return list;
    }

    @Override
    public MangaSummary getDetailedInfo(MangaInfo mangaInfo) {
        try {
            MangaSummary summary = new MangaSummary(mangaInfo);
            Document document = getPage(mangaInfo.path);
            Element e = document.body();
            summary.description = Html.fromHtml(e.select("div.well").first().select("p").html()).toString().trim();
            summary.preview = e.select("div.boxed").first().select("img").first().attr("src");
            MangaChapter chapter;
            e = e.selectFirst("ul.chapters");
            for (Element o : e.select("a")) {
                chapter = new MangaChapter();
                chapter.name = o.text();
                chapter.readLink = o.attr("href");
                chapter.provider = summary.provider;
                summary.chapters.add(0, chapter);
            }
            summary.chapters.enumerate();
            return summary;
        } catch (Exception e) {
            return null;
        }
    }

    @Override
    public ArrayList<MangaPage> getPages(String readLink) {
        ArrayList<MangaPage> pages = new ArrayList<>();
        try {
            Document document = getPage(readLink);
            MangaPage page;
            Element e = document.body().getElementById("all");
            for (Element o : e.select("img")) {
                page = new MangaPage(o.attr("data-src").replaceFirst("http:/", "https:/"));
                page.provider = OnManga.class;
                pages.add(page);
            }
            return pages;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    @Override
    public String getPageImage(MangaPage mangaPage) {
        return mangaPage.path;
    }

    @Nullable
    @Override
    public MangaList search(String query, int page) throws Exception {
        if (page > 0) {
            return null;
        }
        MangaList list = new MangaList();
        JSONObject jo = new JSONObject(getRaw(
                "https://www.on-manga.me/search?query=" + URLEncoder.encode(query, "UTF-8")
        ));
        MangaInfo manga;
        JSONArray ja = jo.getJSONArray("suggestions");
        for (int i = 0; i < ja.length(); i++) {
            jo = ja.getJSONObject(i);
            manga = new MangaInfo();
            manga.name = jo.getString("value");
            manga.path = "https://www.on-manga.me/manga/" + jo.getString("data");
            manga.preview = "https://www.on-manga.me/uploads/manga/" + jo.getString("data") +
                    "/cover/cover_250x350.jpg";
            manga.provider = OnManga.class;
            manga.id = manga.path.hashCode();
            list.add(manga);
        }
        return list;
    }

    @Override
    public boolean isSearchAvailable() {
        return true;
    }

    @Nullable
    @Override
    public String[] getSortTitles(Context context) {
        return AppHelper.getStringArray(context, sorts);
    }

    @Override
    public boolean hasSort() {
        return true;
    }

    @Override
    public boolean hasGenres() {
        return true;
    }

    @Nullable
    @Override
    public String[] getGenresTitles(Context context) {
        return AppHelper.getStringArray(context, genres);
    }

    @Override
    public String getName() {
        return "OnManga";
    }
}
`

can u help me __,

**Comment by Koitharu** [comment]
You need to add line into
https://github.com/nv95/OpenManga/blob/devel/app/src/main/java/org/nv95/openmanga/providers/staff/Providers.java

**Comment by midou221** [comment]
> You need to add line into
> https://github.com/nv95/OpenManga/blob/devel/app/src/main/java/org/nv95/openmanga/providers/staff/Providers.java

Thanks for your quick reply bro
yes i have already added this line

The problem is the server is working but isn't shows nothing (as shown in the picture below) 
https://ibb.co/648DKrt

**Comment by Koitharu** [comment]
Try to debug you getList function

On first look, line 
 ```for (Element o : document.select("stylesheet"))``` is wrong, but I'm not sure

**Comment by midou221** [comment]
> Try to debug you getList function
> 
> On first look, line
> `for (Element o : document.select("stylesheet"))` is wrong, but I'm not sure


thank you very much bro :smile: :smiley: 
The problem has been solved im actually thankful to you
Your application is very cool, i really enjoyed dealing with it ,although im very novice

https://ibb.co/K2fPtyF
