### ISSUE TITLE
Reading manga bug

### ISSUE THREAD

**Issue by Pavkazzz** [nv95/OpenManga#9]
When u slide to another picture in horizontal layout and with zoom, zoom will in center at the picture, not at the top, as expected.

Когда свайпаешь на другую картинку при горизантальной ориентацией и масштабирование (увеличенным), то картинка будет посередине, а не сверху как ожидалось.

**Comment by Pavkazzz** [comment]
1920x1080 resolution.

**Comment by Koitharu** [comment]
Implemented in the new reader
